# Generated by Django 6.0.7 on 2026-07-30 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('media_type', models.CharField(choices=[('Photographs', 'Photographs'), ('Audio Visual', 'Audio Visual')], default='Photographs', max_length=32)),
                ('published_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('serial_no', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('rows', models.TextField(help_text='One contact row per line.')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('href', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='default', max_length=32, unique=True)),
                ('site_name', models.CharField(max_length=255)),
                ('ministry', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('toll_free', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('admin_user', models.CharField(default='admin', max_length=150)),
                ('admin_password', models.CharField(default='admin123', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('section', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('agency_type', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Expired', 'Expired')], default='Active', max_length=16)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['agency_type', 'status'], name='core_agency_agency__aeb0f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('published_at', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['category', '-published_at'], name='core_conten_categor_963ae6_idx'), models.Index(fields=['featured', '-published_at'], name='core_conten_feature_0b0a63_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=120)),
                ('vacancies', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('salary', models.CharField(blank=True, max_length=120)),
                ('contract', models.CharField(blank=True, max_length=120)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=16)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'deadline'], name='core_job_status_7ccdde_idx')],
            },
        ),
    ]
