# Generated by Django 6.0.7 on 2026-07-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gsc_verification',
            field=models.CharField(blank=True, help_text='Google Search Console HTML-tag verification token', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(blank=True, help_text='Public frontend origin, e.g. https://dofe.gov.np'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
    ]
