# Generated by Django 6.0.7 on 2026-08-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='division',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
