# Generated by Django 6.0.7 on 2026-07-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('apply_path', models.CharField(blank=True, default='/online-registration', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Career Opening',
                'verbose_name_plural': 'Career Openings',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_nav', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CMS Page',
                'verbose_name_plural': 'CMS Pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('file', models.FileField(upload_to='media-library/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(help_text='e.g. /, /about, /contact', max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('other', 'Other')], max_length=40)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Partner / Client', 'verbose_name_plural': 'Partners / Clients'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Hero Slide', 'verbose_name_plural': 'Hero Slides'},
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='memberships/'),
        ),
        migrations.AddField(
            model_name='membership',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mottostep',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon key, e.g. listen, plan', max_length=80),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationlink'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registrationsubmission',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='sector',
            name='icon',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sectors/'),
        ),
        migrations.AddField(
            model_name='sector',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ethic_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ethic_button_label',
            field=models.CharField(blank=True, default='Learn More', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ethic_button_path',
            field=models.CharField(blank=True, default='/about', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ethic_eyebrow',
            field=models.CharField(blank=True, default='What we do', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ethic_heading',
            field=models.CharField(blank=True, default='Ethical Recruitment', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hiring_button_label',
            field=models.CharField(blank=True, default='APPLY NOW', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hiring_button_path',
            field=models.CharField(blank=True, default='/online-registration', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hiring_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hiring_heading',
            field=models.CharField(blank=True, default='WE ARE HIRING!', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hiring_subheading',
            field=models.CharField(blank=True, default='Open Positions', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='license_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partner_cta_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partner_cta_button_label',
            field=models.CharField(blank=True, default='Contact Us', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partner_cta_button_path',
            field=models.CharField(blank=True, default='/contact', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partner_cta_heading',
            field=models.CharField(blank=True, default='Partner With Us', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='map_embed_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='DemandList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('employer', models.CharField(blank=True, max_length=180)),
                ('positions', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='demands/')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='core.country')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='core.sector')),
            ],
            options={
                'verbose_name': 'Demand List Item',
                'verbose_name_plural': 'Demand List',
                'ordering': ['-published_at', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.galleryalbum')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
