# Generated by Django 6.0.7 on 2026-07-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enhance_cms_dynamic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('page', models.CharField(choices=[('about', 'About Us'), ('services', 'Services'), ('overseas-recruitment', 'Overseas Recruitment'), ('home', 'Home'), ('careers', 'Careers'), ('contact', 'Contact'), ('awards', 'Awards'), ('gallery', 'Gallery'), ('demands', 'Demands'), ('vacancies', 'Vacancies'), ('other', 'Other')], db_index=True, max_length=60)),
                ('label', models.CharField(help_text='Admin-friendly name', max_length=160)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('body_2', models.TextField(blank=True)),
                ('body_3', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_path', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['page', 'order', 'id'],
            },
        ),
    ]
