# Generated by Django 6.0.7 on 2026-08-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ethical_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
