# Generated by Django 6.0.7 on 2026-08-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certificate_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestatistic',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon key: users, wrench, globe, star, briefcase, map-pin, etc.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='clients_heading',
            field=models.CharField(blank=True, default='PROUD TO WORK WITH', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='expertise_button_label',
            field=models.CharField(blank=True, default='Learn More', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='expertise_button_path',
            field=models.CharField(blank=True, default='/services', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='expertise_heading',
            field=models.CharField(blank=True, default='Our Expertise', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='expertise_intro',
            field=models.TextField(blank=True, default='Our capacity enables us to provide highly qualified employees in the following sectors, without compromising on quality.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='membership_heading',
            field=models.CharField(blank=True, default='Membership', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='motto_heading',
            field=models.CharField(blank=True, default='Our Motto', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='motto_intro',
            field=models.TextField(blank=True, default='At Vision we always deliver by following a simple policy- when it comes to our clients, we simply'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partnership_form_email_label',
            field=models.CharField(blank=True, default='Email', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partnership_form_heading',
            field=models.CharField(blank=True, default='Partner With Us', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partnership_form_message_label',
            field=models.CharField(blank=True, default='Message', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partnership_form_name_label',
            field=models.CharField(blank=True, default='Full name', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partnership_form_phone_label',
            field=models.CharField(blank=True, default='Phone', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partnership_form_sending_label',
            field=models.CharField(blank=True, default='Sending…', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partnership_form_submit_label',
            field=models.CharField(blank=True, default='Submit', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partnership_form_success',
            field=models.TextField(blank=True, default='Thank you — we received your message and will reply shortly.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stats_background',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='testimonials_background',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='testimonials_heading',
            field=models.CharField(blank=True, default='Testimonial', max_length=120),
        ),
    ]
