/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemandsRouteImport } from './routes/demands'
import { Route as EthicalRecruitmentRouteImport } from './routes/ethical-recruitment'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as OnlineRegistrationRouteImport } from './routes/online-registration'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VacanciesRouteImport } from './routes/vacancies'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAboutRouteImport } from './routes/admin/about'
import { Route as AdminAwardsRouteImport } from './routes/admin/awards'
import { Route as AdminCareersRouteImport } from './routes/admin/careers'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminDemandsRouteImport } from './routes/admin/demands'
import { Route as AdminEthicalRecruitmentRouteImport } from './routes/admin/ethical-recruitment'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminHomeRouteImport } from './routes/admin/home'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMethodologyRouteImport } from './routes/admin/methodology'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminOverseasRecruitmentRouteImport } from './routes/admin/overseas-recruitment'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin/site-settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesOverseasRecruitmentRouteImport } from './routes/services.overseas-recruitment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandsRoute = DemandsRouteImport.update({
  id: '/demands',
  path: '/demands',
  getParentRoute: () => rootRouteImport,
} as any)
const EthicalRecruitmentRoute = EthicalRecruitmentRouteImport.update({
  id: '/ethical-recruitment',
  path: '/ethical-recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRegistrationRoute = OnlineRegistrationRouteImport.update({
  id: '/online-registration',
  path: '/online-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesRoute = VacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAwardsRoute = AdminAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDemandsRoute = AdminDemandsRouteImport.update({
  id: '/demands',
  path: '/demands',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEthicalRecruitmentRoute = AdminEthicalRecruitmentRouteImport.update({
  id: '/ethical-recruitment',
  path: '/ethical-recruitment',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMethodologyRoute = AdminMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOverseasRecruitmentRoute =
  AdminOverseasRecruitmentRouteImport.update({
    id: '/overseas-recruitment',
    path: '/overseas-recruitment',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesOverseasRecruitmentRoute =
  ServicesOverseasRecruitmentRouteImport.update({
    id: '/overseas-recruitment',
    path: '/overseas-recruitment',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/demands': typeof DemandsRoute
  '/ethical-recruitment': typeof EthicalRecruitmentRoute
  '/gallery': typeof GalleryRoute
  '/methodology': typeof MethodologyRoute
  '/online-registration': typeof OnlineRegistrationRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/vacancies': typeof VacanciesRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/demands': typeof AdminDemandsRoute
  '/admin/ethical-recruitment': typeof AdminEthicalRecruitmentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/methodology': typeof AdminMethodologyRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/overseas-recruitment': typeof AdminOverseasRecruitmentRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/news/$slug': typeof NewsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/services/overseas-recruitment': typeof ServicesOverseasRecruitmentRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/demands': typeof DemandsRoute
  '/ethical-recruitment': typeof EthicalRecruitmentRoute
  '/gallery': typeof GalleryRoute
  '/methodology': typeof MethodologyRoute
  '/online-registration': typeof OnlineRegistrationRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vacancies': typeof VacanciesRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/demands': typeof AdminDemandsRoute
  '/admin/ethical-recruitment': typeof AdminEthicalRecruitmentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/methodology': typeof AdminMethodologyRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/overseas-recruitment': typeof AdminOverseasRecruitmentRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/news/$slug': typeof NewsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/services/overseas-recruitment': typeof ServicesOverseasRecruitmentRoute
  '/admin': typeof AdminIndexRoute
  '/news': typeof NewsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/demands': typeof DemandsRoute
  '/ethical-recruitment': typeof EthicalRecruitmentRoute
  '/gallery': typeof GalleryRoute
  '/methodology': typeof MethodologyRoute
  '/online-registration': typeof OnlineRegistrationRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/vacancies': typeof VacanciesRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/demands': typeof AdminDemandsRoute
  '/admin/ethical-recruitment': typeof AdminEthicalRecruitmentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/methodology': typeof AdminMethodologyRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/overseas-recruitment': typeof AdminOverseasRecruitmentRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/news/$slug': typeof NewsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/services/overseas-recruitment': typeof ServicesOverseasRecruitmentRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/awards'
    | '/careers'
    | '/contact'
    | '/demands'
    | '/ethical-recruitment'
    | '/gallery'
    | '/methodology'
    | '/online-registration'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/vacancies'
    | '/admin/about'
    | '/admin/awards'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/content'
    | '/admin/demands'
    | '/admin/ethical-recruitment'
    | '/admin/gallery'
    | '/admin/home'
    | '/admin/inquiries'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/methodology'
    | '/admin/news'
    | '/admin/overseas-recruitment'
    | '/admin/registrations'
    | '/admin/services'
    | '/admin/site-settings'
    | '/admin/users'
    | '/news/$slug'
    | '/pages/$slug'
    | '/services/overseas-recruitment'
    | '/admin/'
    | '/news/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/awards'
    | '/careers'
    | '/contact'
    | '/demands'
    | '/ethical-recruitment'
    | '/gallery'
    | '/methodology'
    | '/online-registration'
    | '/privacy'
    | '/terms'
    | '/vacancies'
    | '/admin/about'
    | '/admin/awards'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/content'
    | '/admin/demands'
    | '/admin/ethical-recruitment'
    | '/admin/gallery'
    | '/admin/home'
    | '/admin/inquiries'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/methodology'
    | '/admin/news'
    | '/admin/overseas-recruitment'
    | '/admin/registrations'
    | '/admin/services'
    | '/admin/site-settings'
    | '/admin/users'
    | '/news/$slug'
    | '/pages/$slug'
    | '/services/overseas-recruitment'
    | '/admin'
    | '/news'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/awards'
    | '/careers'
    | '/contact'
    | '/demands'
    | '/ethical-recruitment'
    | '/gallery'
    | '/methodology'
    | '/online-registration'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/vacancies'
    | '/admin/about'
    | '/admin/awards'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/content'
    | '/admin/demands'
    | '/admin/ethical-recruitment'
    | '/admin/gallery'
    | '/admin/home'
    | '/admin/inquiries'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/methodology'
    | '/admin/news'
    | '/admin/overseas-recruitment'
    | '/admin/registrations'
    | '/admin/services'
    | '/admin/site-settings'
    | '/admin/users'
    | '/news/$slug'
    | '/pages/$slug'
    | '/services/overseas-recruitment'
    | '/admin/'
    | '/news/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AwardsRoute: typeof AwardsRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DemandsRoute: typeof DemandsRoute
  EthicalRecruitmentRoute: typeof EthicalRecruitmentRoute
  GalleryRoute: typeof GalleryRoute
  MethodologyRoute: typeof MethodologyRoute
  OnlineRegistrationRoute: typeof OnlineRegistrationRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  VacanciesRoute: typeof VacanciesRoute
  NewsSlugRoute: typeof NewsSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demands': {
      id: '/demands'
      path: '/demands'
      fullPath: '/demands'
      preLoaderRoute: typeof DemandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethical-recruitment': {
      id: '/ethical-recruitment'
      path: '/ethical-recruitment'
      fullPath: '/ethical-recruitment'
      preLoaderRoute: typeof EthicalRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-registration': {
      id: '/online-registration'
      path: '/online-registration'
      fullPath: '/online-registration'
      preLoaderRoute: typeof OnlineRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies': {
      id: '/vacancies'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof VacanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/awards': {
      id: '/admin/awards'
      path: '/awards'
      fullPath: '/admin/awards'
      preLoaderRoute: typeof AdminAwardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/demands': {
      id: '/admin/demands'
      path: '/demands'
      fullPath: '/admin/demands'
      preLoaderRoute: typeof AdminDemandsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ethical-recruitment': {
      id: '/admin/ethical-recruitment'
      path: '/ethical-recruitment'
      fullPath: '/admin/ethical-recruitment'
      preLoaderRoute: typeof AdminEthicalRecruitmentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/methodology': {
      id: '/admin/methodology'
      path: '/methodology'
      fullPath: '/admin/methodology'
      preLoaderRoute: typeof AdminMethodologyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/overseas-recruitment': {
      id: '/admin/overseas-recruitment'
      path: '/overseas-recruitment'
      fullPath: '/admin/overseas-recruitment'
      preLoaderRoute: typeof AdminOverseasRecruitmentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/overseas-recruitment': {
      id: '/services/overseas-recruitment'
      path: '/overseas-recruitment'
      fullPath: '/services/overseas-recruitment'
      preLoaderRoute: typeof ServicesOverseasRecruitmentRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminAwardsRoute: typeof AdminAwardsRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDemandsRoute: typeof AdminDemandsRoute
  AdminEthicalRecruitmentRoute: typeof AdminEthicalRecruitmentRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMethodologyRoute: typeof AdminMethodologyRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminOverseasRecruitmentRoute: typeof AdminOverseasRecruitmentRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminAwardsRoute: AdminAwardsRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminContactRoute: AdminContactRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDemandsRoute: AdminDemandsRoute,
  AdminEthicalRecruitmentRoute: AdminEthicalRecruitmentRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMethodologyRoute: AdminMethodologyRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminOverseasRecruitmentRoute: AdminOverseasRecruitmentRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ServicesRouteChildren {
  ServicesOverseasRecruitmentRoute: typeof ServicesOverseasRecruitmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesOverseasRecruitmentRoute: ServicesOverseasRecruitmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AwardsRoute: AwardsRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DemandsRoute: DemandsRoute,
  EthicalRecruitmentRoute: EthicalRecruitmentRoute,
  GalleryRoute: GalleryRoute,
  MethodologyRoute: MethodologyRoute,
  OnlineRegistrationRoute: OnlineRegistrationRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  VacanciesRoute: VacanciesRoute,
  NewsSlugRoute: NewsSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
