/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesListRouteImport } from './routes/services-list'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgenciesRouteImport } from './routes/admin.agencies'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminContentsRouteImport } from './routes/admin.contents'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminOfficialsRouteImport } from './routes/admin.officials'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ContentIdRouteImport } from './routes/content.$id'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesListRoute = ServicesListRouteImport.update({
  id: '/services-list',
  path: '/services-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenciesRoute = AdminAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentsRoute = AdminContentsRouteImport.update({
  id: '/contents',
  path: '/contents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfficialsRoute = AdminOfficialsRouteImport.update({
  id: '/officials',
  path: '/officials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/our-team': typeof OurTeamRoute
  '/search': typeof SearchRoute
  '/services-list': typeof ServicesListRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/contents': typeof AdminContentsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/officials': typeof AdminOfficialsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/category/$slug': typeof CategorySlugRoute
  '/content/$id': typeof ContentIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/our-team': typeof OurTeamRoute
  '/search': typeof SearchRoute
  '/services-list': typeof ServicesListRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/contents': typeof AdminContentsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/officials': typeof AdminOfficialsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/category/$slug': typeof CategorySlugRoute
  '/content/$id': typeof ContentIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/our-team': typeof OurTeamRoute
  '/search': typeof SearchRoute
  '/services-list': typeof ServicesListRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/contents': typeof AdminContentsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/officials': typeof AdminOfficialsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/category/$slug': typeof CategorySlugRoute
  '/content/$id': typeof ContentIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact-us'
    | '/gallery'
    | '/jobs'
    | '/our-team'
    | '/search'
    | '/services-list'
    | '/admin/agencies'
    | '/admin/contacts'
    | '/admin/contents'
    | '/admin/gallery'
    | '/admin/jobs'
    | '/admin/officials'
    | '/admin/pages'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/category/$slug'
    | '/content/$id'
    | '/pages/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-us'
    | '/gallery'
    | '/jobs'
    | '/our-team'
    | '/search'
    | '/services-list'
    | '/admin/agencies'
    | '/admin/contacts'
    | '/admin/contents'
    | '/admin/gallery'
    | '/admin/jobs'
    | '/admin/officials'
    | '/admin/pages'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/category/$slug'
    | '/content/$id'
    | '/pages/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact-us'
    | '/gallery'
    | '/jobs'
    | '/our-team'
    | '/search'
    | '/services-list'
    | '/admin/agencies'
    | '/admin/contacts'
    | '/admin/contents'
    | '/admin/gallery'
    | '/admin/jobs'
    | '/admin/officials'
    | '/admin/pages'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/category/$slug'
    | '/content/$id'
    | '/pages/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactUsRoute: typeof ContactUsRoute
  GalleryRoute: typeof GalleryRoute
  JobsRoute: typeof JobsRoute
  OurTeamRoute: typeof OurTeamRoute
  SearchRoute: typeof SearchRoute
  ServicesListRoute: typeof ServicesListRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ContentIdRoute: typeof ContentIdRoute
  PagesSlugRoute: typeof PagesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services-list': {
      id: '/services-list'
      path: '/services-list'
      fullPath: '/services-list'
      preLoaderRoute: typeof ServicesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agencies': {
      id: '/admin/agencies'
      path: '/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AdminAgenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contents': {
      id: '/admin/contents'
      path: '/contents'
      fullPath: '/admin/contents'
      preLoaderRoute: typeof AdminContentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/officials': {
      id: '/admin/officials'
      path: '/officials'
      fullPath: '/admin/officials'
      preLoaderRoute: typeof AdminOfficialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAgenciesRoute: typeof AdminAgenciesRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminContentsRoute: typeof AdminContentsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminOfficialsRoute: typeof AdminOfficialsRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgenciesRoute: AdminAgenciesRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminContentsRoute: AdminContentsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminOfficialsRoute: AdminOfficialsRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactUsRoute: ContactUsRoute,
  GalleryRoute: GalleryRoute,
  JobsRoute: JobsRoute,
  OurTeamRoute: OurTeamRoute,
  SearchRoute: SearchRoute,
  ServicesListRoute: ServicesListRoute,
  CategorySlugRoute: CategorySlugRoute,
  ContentIdRoute: ContentIdRoute,
  PagesSlugRoute: PagesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
